language: csharp
solution: DemoInfo.sln
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y mono-profiler python-pip
  - sudo pip install --upgrade requests
before_script:
  - git clone 'https://github.com/main--/demoinfo-testdata.git' testdemos
  - "[ \"$TRAVIS_PULL_REQUEST\" = \"true\" ] || bash ci/nuget_set_api_key.sh"
script:
  - nuget restore DemoInfo.sln
  - xbuild /p:Configuration=Bitstream-Debugging DemoInfo.sln
  - xbuild /p:Configuration=Release DemoInfo.sln
  - mono packages/NUnit.Runners.2.6.4/tools/nunit-console.exe -noxml -nodots -labels Testing/bin/Release/Testing.dll
  - python ci/brofiler.py verify
  - python ci/brofiler.py run
after_success:
  - "[ \"$TRAVIS_PULL_REQUEST\" = \"true\" ] || [ \"$TRAVIS_BRANCH\" != \"master\" ] || sed -i \"s/<\\/version>/-ci$(date +%s)-$(git rev-parse --short HEAD)<\\/version>/\" DemoInfo.nuspec && nuget pack DemoInfo.nuspec && nuget push *.nupkg"
after_script:
  - python ci/brofiler.py cleanup
